[package]
name = "Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
yt-dlp = { version = "1.4.7", features = ["tracing"] }
tokio = { version = "1.49.0", features = ["full"] }
file-guard = "0.2"